### PR TITLE
Update GHA for coveralls

### PR DESCRIPTION
**Pull request by ronaldtse**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@maxirmx could you please help switch from the coveralls command to the GHA action? 

The difference is that the GHA coveralls action doesn’t require the repo secret, which is not to be shared. 

Thanks!

**Comment by maxirmx** [comment]
_{'message': "Couldn't find a repository matching this job.", 'error': True}
Error: Process completed with exit code 1._

It looks like you did not register this repo with coveralls account.  I do not have sufficients rights in metanorma organization to do it on your behalf.

**Comment by maxirmx** [comment]
cpp-coveralls is not compatible with GitHub actions since it deletes .lcov files that are required by GHA.

The easiest method to keep secret secret is:
1. Register the repo with metanorma coveralls account
2. Generate coveralls secret key for this repo
3. Update repo secret COVERALLS_REPO_TOKEN with this secret key
4. Use the following command to push report to coveralls.io
_- name: Report
      run: coveralls -t ${{ secrets.COVERALLS_REPO_TOKEN }} -E '.*CMakeFiles.*' -E '.*conv.*' -E '.*uemf.*' -E '.*upmf.*' -E '.*goodies.*' -E '.*tests.*' --gcov-options '\-lp'_

You can see it working at maxirmx fork.

**Comment by ronaldtse** [comment]
This is implemented now. Thanks @maxirmx !

**Pull request merged**
